import { isFirebaseEnabled, saveConfig, clearConfig, getConfig, migrateLocalDataToFirestore } from "./config";
import { getProducts, getLowStockCount, getLowStockProducts, saveProduct, deleteProduct, addStockAdjustment, getStockAdjustments, initStockAdjustmentsListener, initProductsListener } from "./products";
import { getTransactions, addTransaction, deleteTransaction, returnTransaction, updateTransactionPaymentMode, initTransactionsListener } from "./transactions";
import { getCustomers, saveCustomer, updateUdhaarBalance, initCustomersListener } from "./customers";
import { login, logout, getCurrentUser, onAuthStateChangedListener, initUsersListener } from "./auth";
import { getExpenses, addExpense, deleteExpense, EXPENSE_CATEGORIES } from "./expenses";
import {
  getBalance, getAllBalances, adjustBalance,
  initiateTransfer, approveTransfer, rejectTransfer,
  getPendingForUser, getPendingCount,
  getHistoryForUser, getAllTransactions, initCOHListener,
} from "./coh";
import { recordPriceChange, getPriceHistory, getAllPriceHistory, clearPriceHistory } from "./priceHistory";
import { getPurchaseOrders, savePurchaseOrder, receivePurchaseOrder, cancelPurchaseOrder, updatePurchaseOrder, updatePurchaseOrderPaymentMode } from "./purchases";
import { getSuppliers, saveSupplier, deleteSupplier, updateSupplierBalance, adjustSupplierBalance, recordSupplierPayment, initSuppliersListener } from "./suppliers";
import { initFinanceListener, getBanks, addBank, updateBank, deleteBank, getFinanceTransactions, financeTransfer } from "./finance";
import { initSettingsListener, saveAppSettings } from "./settings";
import { initAuditListener, getAuditLogs, logAudit } from "./audit";
import { getAccounts, saveAccount, deleteAccount, getEntries, addEntry, deleteEntry, initCOAListener, ACCOUNT_TYPES, SYSTEM_ACCOUNTS } from "./coa";
import { getPaymentModes, savePaymentMode, deletePaymentMode } from "./paymentModes";
import { factoryReset } from "./reset";

export const dbService = {
  isFirebase: () => isFirebaseEnabled,
  saveConfig,
  clearConfig,
  getConfig,
  getProducts,
  getLowStockCount,
  getLowStockProducts,
  getPurchaseOrders,
  savePurchaseOrder,
  receivePurchaseOrder,
  cancelPurchaseOrder,
  updatePurchaseOrder,
  updatePurchaseOrderPaymentMode,
  saveProduct,
  deleteProduct,
  addStockAdjustment,
  getStockAdjustments,
  initStockAdjustmentsListener,
  initProductsListener,
  getTransactions,
  addTransaction,
  deleteTransaction,
  returnTransaction,
  updateTransactionPaymentMode,
  initTransactionsListener,
  getCustomers,
  saveCustomer,
  updateUdhaarBalance,
  initCustomersListener,
  getExpenses,
  addExpense,
  deleteExpense,
  EXPENSE_CATEGORIES,
  login,
  logout,
  getCurrentUser,
  onAuthStateChangedListener,
  initUsersListener,
  getBalance,
  getAllBalances,
  adjustBalance,
  initiateTransfer,
  approveTransfer,
  rejectTransfer,
  getPendingForUser,
  getPendingCount,
  getHistoryForUser,
  getAllTransactions: getAllTransactions,
  initCOHListener,
  recordPriceChange,
  getPriceHistory,
  getAllPriceHistory,
  clearPriceHistory,
  getSuppliers,
  saveSupplier,
  deleteSupplier,
  updateSupplierBalance,
  adjustSupplierBalance,
  recordSupplierPayment,
  initSuppliersListener,
  migrateLocalDataToFirestore,
  getPaymentModes,
  savePaymentMode,
  deletePaymentMode,
  initFinanceListener,
  initSettingsListener,
  initAuditListener,
  getAuditLogs,
  logAudit,
  saveAppSettings,
  getBanks,
  addBank,
  updateBank,
  deleteBank,
  getFinanceTransactions,
  financeTransfer,
  getCoaAccounts: getAccounts,
  saveCoaAccount: saveAccount,
  deleteCoaAccount: deleteAccount,
  getCoaEntries: getEntries,
  addCoaEntry: addEntry,
  deleteCoaEntry: deleteEntry,
  initCOAListener,
  ACCOUNT_TYPES,
  SYSTEM_ACCOUNTS,
  factoryReset,
};
